### ISSUE TITLE
Add ability to add a new node or change type of a node.

### ISSUE THREAD

**Issue by alextrukhan** [sergeyzwezdin/magic-chunks#63]
Add ability to add or change node type:
For example: [see possible docker compose file](https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on) states for the same node depends_on. the depends_on can be an array or can be a root element for other nodes. Could I change a yml like this
```
depends_on:
  - db
  - redis
```
to this
```
depends_on:
  db:
    condition: service_healthy
  redis:
    condition: service_started
```
?
