### ISSUE TITLE
Transforming directory pathh adds extra slashes "\\"

### ISSUE THREAD

**Issue by sunilbindra** [sergeyzwezdin/magic-chunks#78]
I am suing Magic chunks. In my master json file I have one key with value

 "ExternalFiles": {
    "EncryptionKeyFile": "C:\\TotalKeys\\key.config.json"
  }
In my transformation file transforming it to I have this 

"ExternalFiles/EncryptionKeyFile": "C:\\TotalKeys\\keytest.config.json"

When it transform result is having some extra slashes, dont know why:-

"ExternalFiles": {
    "EncryptionKeyFile": "C:\\\\TotalKeys\\\\keytest.config.json"
  }

Any Idea why there are extra "\\". it got 4 instead of 2.
Thanks

**Comment by sourcejon** [comment]
bump

**Comment by nils-a** [comment]
@sourcejon, @sunilbindra I wanted to have a look at this, but could not reproduce it.
Would one of you be in a position to provide a minimal example that reproduces the error?

**Comment by nils-a** [comment]
Found it. This happens, when using the DevOps Task and "correctly" escaping `\` in json of the transformation.

I.e. when the task is defined like:
```yaml
- task: MagicChunks@2
  inputs:
    sourcePath: 'test.json'
    fileType: 'Auto'
    targetPathType: 'source'
    transformationType: 'json'
    transformations: |
      {
        "ExternalFiles/EncryptionKeyFile": 
              "C:\\TotalKeys\\keytest.config.json"
      }
```
(notice the double `\\` in the transformations) - the error occurs. 

However, if the transformation-json is defined ("wrongly") as 

```yaml
- task: MagicChunks@2
  inputs:
    sourcePath: 'test.json'
    fileType: 'Auto'
    targetPathType: 'source'
    transformationType: 'json'
    transformations: |
      {
        "ExternalFiles/EncryptionKeyFile": 
              "C:\TotalKeys\keytest.config.json"
      }
```

(notice the single `\` in the transformations) - the error does not occur. 

This behavior is the same, regardless whether one is using the "Inline JSON" transformation type or the "JSON File" type.
